[project]
name = "axiomlm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sentencepiece>=0.2.1",
    "tensorflow>=2.20.0",
]
